const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 79.99,
      category: "Electronics",
      stock: 25,
      rating: 4.5,
      description: "High-quality wireless headphones with noise cancellation.",
    },
    {
      id: 2,
      name: "Smartwatch",
      price: 149.99,
      category: "Wearable Tech",
      stock: 15,
      rating: 4.7,
      description: "Feature-packed smartwatch with health tracking and notifications.",
    },
    {
      id: 3,
      name: "Gaming Keyboard",
      price: 59.99,
      category: "Computer Accessories",
      stock: 40,
      rating: 4.6,
      description: "Mechanical RGB gaming keyboard with customizable keys.",
    },
    {
      id: 4,
      name: "Bluetooth Speaker",
      price: 39.99,
      category: "Audio",
      stock: 0,
      rating: 4.4,
      description: "Portable Bluetooth speaker with deep bass and long battery life.",
    },
    {
      id: 5,
      name: "Laptop Stand",
      price: 29.99,
      category: "Office Accessories",
      stock: 50,
      rating: 4.3,
      description: "Ergonomic aluminum laptop stand for better posture and cooling.",
    },
    {
      id: 6,
      name: "Wireless Mouse",
      price: 19.99,
      category: "Computer Accessories",
      stock: 60,
      rating: 4.5,
      description: "Smooth and responsive wireless mouse with adjustable DPI.",
    },
    {
      id: 7,
      name: "4K Monitor",
      price: 299.99,
      category: "Electronics",
      stock: 0,
      rating: 4.8,
      description: "Ultra HD 4K monitor with vibrant colors and high refresh rate.",
    },
    {
      id: 8,
      name: "External Hard Drive",
      price: 89.99,
      category: "Storage",
      stock: 20,
      rating: 4.6,
      description: "2TB external hard drive for secure and fast data storage.",
    },
    {
      id: 9,
      name: "Smart LED Bulb",
      price: 12.99,
      category: "Home Automation",
      stock: 100,
      rating: 4.2,
      description: "WiFi-enabled LED bulb with adjustable colors and brightness.",
    },
    {
      id: 10,
      name: "Fitness Tracker",
      price: 39.99,
      category: "Wearable Tech",
      stock: 35,
      rating: 4.5,
      description: "Lightweight fitness tracker with heart rate and step tracking.",
    }
  ];
  
export default products;
  